# Generated by Django 5.1.6 on 2025-03-12 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('professor', 'Professor'), ('aluno', 'Aluno'), ('outro', 'Outro')], max_length=10)),
                ('equipamento', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('problema', models.TextField()),
                ('outro_equipamento_entregue', models.CharField(default='Carregador', max_length=100)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('permite_abrir_pc', models.BooleanField(default=True)),
                ('data_recepcao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('em_reparacao', 'Em Reparação'), ('reparado', 'Reparado'), ('entregue', 'Entregue')], default='recebido', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intervencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_intervencao', models.DateField(auto_now_add=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('descricao', models.TextField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.tecnico')),
            ],
        ),
    ]
