# Generated by Django 5.1.6 on 2025-03-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data_recepcao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='password',
            field=models.CharField(default='Não Tem', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('em_reparacao', 'Em Reparação'), ('reparado', 'Reparado'), ('entregue', 'Entregue')], default='Recebido', max_length=15),
        ),
    ]
