# Generated by Django 5.1.6 on 2025-03-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_alter_equipamento_data_recepcao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='apagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('Recebido', 'Recebido'), ('Em Reparacao', 'Em Reparação'), ('Reparado', 'Reparado'), ('Entregue', 'Entregue')], default='Recebido', max_length=15),
        ),
    ]
