# Generated by Django 5.1.6 on 2025-03-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_equipamento_apagado_alter_equipamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('Recebido', 'Recebido'), ('Em Reparacao', 'Em Reparação'), ('Em Orcamentacao', 'Em Orçamentação'), ('Reparado', 'Reparado'), ('Entregue', 'Entregue')], default='Recebido', max_length=15),
        ),
    ]
