# Generated by Django 5.1.7 on 2025-03-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_equipamento_created_at_equipamento_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data_recepcao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(max_length=50),
        ),
    ]
