# Generated by Django 5.1.7 on 2025-03-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_alter_equipamento_data_recepcao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='permite_apagar_dados',
            field=models.BooleanField(default=True),
        ),
    ]
