# Generated by Django 5.1.7 on 2025-03-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0007_equipamento_permite_apagar_dados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervencao',
            name='data_intervencao',
        ),
        migrations.AlterField(
            model_name='intervencao',
            name='hora_fim',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='intervencao',
            name='hora_inicio',
            field=models.DateTimeField(),
        ),
    ]
