# Generated by Django 5.1.7 on 2025-03-20 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0009_intervencao_apagado_alter_intervencao_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencao',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.tecnico'),
        ),
    ]
